kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storageclass-azurefile
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=0
 - mfsymlinks
 - cache=strict
 - actimeo=30
parameters:
  skuName: Standard_LRS
  storageAccount: <Your-Azure-Storage-Account-Name>
  secretName: azure-storage-secret
  secretNamespace: default