apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-role
subjects:
- kind: ServiceAccount
  name: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:      
      serviceAccountName: vault
      initContainers:
      - name: setup
        image: busybox
        command: ["sh", "-c", "cat /mnt/vault/config/config.hcl", "chmod 777 /mnt/vault/config/config.hcl"]
        volumeMounts:
        - name: vault-config
          mountPath: /mnt/vault/config
          readOnly: false
      containers:
      - name: vault
        image: hashicorp/vault:latest
        imagePullPolicy: Always
        command: ["sh", "-c", "vault server -config=/mnt/vault/config/config.hcl"]
        ports:
        - containerPort: 8200
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        volumeMounts:
        - name: vault-pv
          mountPath: /mnt/vault/data
          readOnly: false
        - name: vault-config
          mountPath: /mnt/vault/config
          readOnly: false
        
      volumes:
      - name: vault-pv
        persistentVolumeClaim:
          claimName: vault-pvc
      - name: vault-config
        configMap:
          name: vault-config